  services: 
    mysqldb:
      image: mysql:8.4
      container_name: nestjs-mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: internship_assignment
        MYSQL_USER: hoangngo
        MYSQL_PASSWORD: 123456
      ports:
        - "3307:3306"
      volumes: 
        # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - mysqldb_data:/var/lib/mysql

  volumes:
    mysqldb_data: